### PR TITLE
feat: bump custom emoji limit to 250 and stickers limit to 50

### LINKED ISSUE #266: [develop | latest] Bump the emoji limit per group chat to 250 emojis
Hi,
After some consideration, we think 100 emojis per GC may be a bit limiting.
Our suggestion is to bump this limit to 250 emojis instead.
I know this sounds a bit extreme, but hear us out:
- This would require creating less GCs, and possibly less accounts.
- cat: 500 * 150 > 250 * 200 (better than discord) (250*200 is assuming you have nitro and are paying $10000/month to boost all your servers to tier 3)
- noodles: more emojis = more better

### PR DESCRIPTION
**Pull request by tnix100**
Closes #266

### CODE REVIEW

**Comment by showierdata9978** [comment]
this should prolly be an env var

**Comment by tnix100** [comment]
> this should prolly be an env var

That's true.

**Review by showierdata9978 — APPROVED** [review]
lgtm other then a nit of the imports being on the same line

**Comment by tnix100** [comment]
> lgtm other then a nit of the imports being on the same line

I personally like them on the same line :p

**Comment by showierdata9978** [comment]
and that's why its a nit

**Pull request merged**
