### PR TITLE
Feat: Pronouns

### LINKED ISSUE #272: add pronouns to user profiles
**Is your feature request related to a problem? Please describe.**
Not knowing what other people's pronouns are. Because you should never assume someone's pronouns.

**Describe the solution you'd like**
A new field on the user object that is structured like this:
```
{
   pronouns: [
          ["he", "him"],
          ["they", "them"]
   ]
}
```

This should also be on the partial user object so clients can render it inline if wanted. 

**Describe alternatives you've considered**
none.

### PR DESCRIPTION
**Pull request by showierdata9978**
closes #272

### CODE REVIEW

**Review by ArrowAced — APPROVED** [review]

**Review by Supernoodles99 — APPROVED** [review]
hamburger

**Comment by theotherhades** [comment]
Nooo they're making Meower woke 🤬🤬🤬

**Comment by showierdata9978** [comment]
> Nooo they're making Meower woke 🤬🤬🤬

this is a joke right?

**Comment by JoshAtticus** [comment]
> Nooo they're making Meower woke 🤬🤬🤬

how could they this is unacceptable we need to boycott meower and use facebook instead 🤬🤬🤬🤬🤬🤬🤬🤬🤬

**Comment by JoshAtticus** [comment]
but being fr, having an array and stuff is too complex, it can just be a single string, like tnix also said on meower, see https://leo.atticat.tech/share/?id=4bff790b-cca9-42e5-834f-99b0868f9680

**Comment by theotherhades** [comment]
I agree with Josh, this seems like an overengineered solution considering the problem it is trying to solve

**Comment by showierdata9978** [comment]
I ain't changing the format

**Comment by JoshAtticus** [comment]
> I ain't changing the format

then this pr should be closed

**Comment by mybearworld** [comment]
It might be a bit difficult to create a UI for entering these like that with clients. I think just using strings would be better.

```json
{
  "pronouns": ["he/him", "they/them"]
}
```

**Comment by tnix100** [comment]
> It might be a bit difficult to create a UI for entering these like that with clients. I think just using strings would be better.
> 
> ```json
> {
>   "pronouns": ["he/him", "they/them"]
> }
> ```

I think this is what's going to be implemented now.

**Comment by showierdata9978** [comment]
yep

**Comment by CST1229** [comment]
I would suggest going the Discord route and just having one text field.
```json
{
"pronouns": "he/they"
}
```

**Comment by showierdata9978** [comment]
that was already 100% ruled out.

**Comment by JoshAtticus** [comment]
> that was already 100% ruled out.

you don't make that decision afaik

**Comment by showierdata9978** [comment]
image

**Comment by JoshAtticus** [comment]
> image

who said it was going to be merged then?

**Review by tnix100 — CHANGES_REQUESTED** [review]
This should be changed to just a string. I still think an array of strings is too much.

**Comment by showierdata9978** [comment]
> This should be changed to just a string. I still think an array of strings is too much.

no

**Comment by mybearworld** [comment]
> This should be changed to just a string. I still think an array of strings is too much.

Why is it too much? It would be nice to be able to have a "preferred" pronoun that could be displayed inline on posts, but to also have another/others that could be displayed on a profile, for instance

**Comment by tnix100** [comment]
> > This should be changed to just a string. I still think an array of strings is too much.
> 
> Why is it too much? It would be nice to be able to have a "preferred" pronoun that could be displayed inline on posts, but to also have another/others that could be displayed on a profile, for instance

You can always use your quote to have more, or link to something like pronouns.page. I don't think Meower as a chat platform needs to have all your pronouns, just the one you most preferred is enough in my opinion.

**Comment by mybearworld** [comment]
> You can always use your quote to have more, or link to something like pronouns.page. I don't think Meower as a chat platform needs to have all your pronouns, just the one you most prefer is enough in my opinion.

That makes sense

**Comment by williamhorning** [comment]
pronoun support is something i'm in favor of adding but the amount of bikeshedding and the focus on rewriting events makes this extremely low priority

**Pull request closed without merging**
